---
name: "Build and Release"
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        config:
          - os: macos-11
            os-friendly: macos11
            python-version: '3.8'
          - os: macos-10.15
            os-friendly: macos10-15
            python-version: '3.8'
          - os: ubuntu-latest
            os-friendly: ubuntu
            python-version: '3.8'
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python for ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.python-version }}
      - name: get/set version
        id: aws-jumpcloud-version
        run: |  
          AWS_JUMPCLOUD_VERSION=$(python3 -c "from aws_jumpcloud.version import __VERSION__; print(__VERSION__)" -i aws_jumpcloud/version.py)
          echo "::set-output name=AWS_JUMPCLOUD_VERSION::${AWS_JUMPCLOUD_VERSION}"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          python3 -m pip install -r test-requirements.txt
          python3 setup.py sdist bdist_wheel
          pex --python-shebang='/usr/bin/env python3' --interpreter-constraint="CPython>=3,<4" -f dist aws-jumpcloud -e aws_jumpcloud.cli:main -o dist/aws_jumpcloud-${{ matrix.config.os-friendly }}-${{ steps.aws-jumpcloud-version.outputs.AWS_JUMPCLOUD_VERSION }}.pex
      - uses: actions/upload-artifact@v2
        with:
          name: aws-jumpcloud-artifacts
          path: dist/*
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: aws-jumpcloud-artifacts
          path: dist/*
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            dist/*
      - uses: actions/checkout@v1
      - name: Release Homebrew Formula
        uses: CirrusMD/github-action-homebrew-release@v1.0.0
        if: ${{ success() }}
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          homebrew-gh-token: ${{ secrets.AWS_JUMPCLOUD_GH_TOKEN }}
          homebrew-repo: CirrusMD/homebrew-aws-jumpcloud
          source-template-path: HomebrewFormula/aws-jumpcloud.rb
